jobs:
  include:
    - os: linux
      dist: xenial
      language: python
      python: "3.6"

before_install:
  - sudo apt-get -y install libevent-dev libjson-c-dev verilator

install:
  # Get Migen / LiteX / Cores
  - pwd
  - ls
  - cd ~/
  - mkdir litex
  - ls
  - cd litex
  - pip3 install requests
  - wget https://raw.githubusercontent.com/enjoy-digital/litex/master/litex_setup.py
  # Get rid of other cores to test only BP
  - sed -i 's/.*pythondata-misc-tapcfg.*//' litex_setup.py
  - sed -i 's/.*pythondata-cpu-lm32.*//' litex_setup.py
  - sed -i 's/.*pythondata-cpu-mor1kx.*//' litex_setup.py
  - sed -i 's/.*pythondata-cpu-picorv32.*//' litex_setup.py
  - sed -i 's/.*pythondata-cpu-serv.*//' litex_setup.py
  - sed -i 's/.*pythondata-cpu-vexriscv.*//' litex_setup.py
  - sed -i 's/.*pythondata-cpu-rocket.*//' litex_setup.py
  - sed -i 's/.*pythondata-cpu-minerva.*//' litex_setup.py
  - sed -i 's/.*pythondata-cpu-microwatt.*//' litex_setup.py
  # Setup LiteX
  - chmod +x litex_setup.py
  - python3 ./litex_setup.py init install dev
  - cd litex/litex/soc/cores/cpu/blackparrot
  - source ./setEnvironment.sh

before_script:
  # Get RISC-V toolchain
  - cd ~/litex
  - python3 ./litex_setup.py gcc
  - ls $PWD/riscv64-*/bin/
  - export PATH=$PATH:$(echo $PWD/riscv64-*/bin/)
  - riscv64-unknown-elf-gcc --version

script:
  - cd ~/linux-on-litex-blackparrot
  - chmod +x test.sh
  - ./test.sh 
